import com.github.rcubedev.utils.build.PatchClasses
import com.github.rcubedev.utils.build.UnitTestIgnoredTransformer

plugins {
    id 'java-library'
    id 'maven-publish'
    id 'jacoco'
    id 'idea'
    id 'me.champeau.jmh' version '0.7.3'
}

version = project.version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

def patchedMainDir = layout.buildDirectory.dir("patched/test/classes/java/main")

repositories {
    mavenCentral()
    /*exclusiveContent {
        forRepository {
            maven {
                url "https://repo.spongepowered.org/repository/maven-public"
                name = "Sponge"
            }
        }
        filter {
            includeGroupAndSubgroups("org.spongepowered")
        }
    }*/
    maven { url 'https://repo.sleeping.town/' }
}

sourceSets {
    integrationTest {
        compileClasspath += sourceSets.main.output + sourceSets.test.output
        runtimeClasspath += sourceSets.main.output + sourceSets.test.output
    }
}

configurations {
    testImplementation.extendsFrom implementation
    testCompileOnly.extendsFrom compileOnly
    testRuntimeOnly.extendsFrom runtimeOnly

    integrationTestImplementation.extendsFrom testImplementation
    integrationTestCompileOnly.extendsFrom testCompileOnly
    integrationTestRuntimeOnly.extendsFrom testRuntimeOnly
    integrationTestAnnotationProcessor.extendsFrom testAnnotationProcessor
}

idea {
    module {
        testSources.from(sourceSets.integrationTest.java.srcDirs)
    }
}

configurations {
    mockitoAgent
}

dependencies {
    api 'folk.sisby:kaleido-config:0.3.3+1.3.2'
    implementation 'com.google.guava:guava:32.1.2-jre'

    implementation 'org.slf4j:slf4j-api:2.0.9'

    compileOnly 'org.jetbrains:annotations:24.1.0'
    //compileOnly 'org.spongepowered:mixin:0.8.5'

    runtimeOnly 'org.apache.logging.log4j:log4j-api:2.22.1'
    runtimeOnly 'org.apache.logging.log4j:log4j-core:2.22.1'
    runtimeOnly 'org.apache.logging.log4j:log4j-slf4j2-impl:2.22.1'

    testImplementation "org.junit.jupiter:junit-jupiter:5.10.2"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"

    mockitoAgent('org.mockito:mockito-core:5.+') { transitive = false }
    testImplementation 'org.mockito:mockito-core:5.+'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.+'

    testImplementation 'net.bytebuddy:byte-buddy:1.18.8'
    testImplementation 'net.bytebuddy:byte-buddy-agent:1.18.8'

    integrationTestAnnotationProcessor sourceSets.main.output
    jmhAnnotationProcessor sourceSets.main.output
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21

    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }

    modularity.inferModulePath = true
}

def archiveNameProvider = project.base.archivesName
jar {
    inputs.property "archivesName", archiveNameProvider

    manifest {
        attributes('FMLModType': 'LIBRARY')
    }

    from("LICENSE") {
        rename { "${it}_${archiveNameProvider.get()}" }
    }
}

// todo: this will be fixed when kaleido becomes module or own config lib
tasks.named('compileJava', JavaCompile) {
    options.compilerArgs.addAll(['--module-path', classpath.asPath])
}

tasks.register('patchClassesForTest', PatchClasses) {
    dependsOn classes
    sourceDirs.from(sourceSets.main.output.classesDirs)
    outputDir.set(patchedMainDir)
    transformer.set(new UnitTestIgnoredTransformer())
}

test {
    useJUnitPlatform()
    dependsOn patchClassesForTest
    finalizedBy jacocoTestReport
    jvmArgs "-javaagent:${configurations.mockitoAgent.asPath}", "-Xshare:off"

    // Swap standard main production output folders out for our isolated sandbox
    classpath = files(patchedMainDir) + (classpath - sourceSets.main.output.classesDirs)
}

jacocoTestReport {
    group = 'verification'
    dependsOn test

    reports {
        html.required = true
    }

    classDirectories.setFrom(files(patchedMainDir))
}

tasks.register('integrationTest', Test) {
    group = 'verification'

    useJUnitPlatform()
    jvmArgs "-javaagent:${configurations.mockitoAgent.asPath}", "-Xshare:off"

    testClassesDirs = sourceSets.integrationTest.output.classesDirs
    classpath = sourceSets.integrationTest.runtimeClasspath + sourceSets.test.runtimeClasspath
    shouldRunAfter test
    finalizedBy jacocoIntegrationTestReport
}

tasks.register('jacocoIntegrationTestReport', JacocoReport) {
    group = 'verification'
    description = 'Generates JaCoCo coverage reports for the integration test suite.'

    dependsOn integrationTest

    executionData integrationTest
    sourceSets sourceSets.main
    reports {
        html.required = true
        xml.outputLocation.set(layout.buildDirectory.file("reports/jacoco/integrationTest/jacocoIntegrationTestReport.xml"))
        html.outputLocation.set(layout.buildDirectory.dir("reports/jacoco/integrationTest"))
    }
}

check.dependsOn integrationTest

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}
