package com.github.rcubedev.utils.event.impl.bus.dispatch.table;

import com.github.rcubedev.utils.event.api.Event;
import com.github.rcubedev.utils.event.impl.bus.dispatch.table.resolver.Resolver;
import org.jetbrains.annotations.NotNull;

import java.util.Collection;

/**
 * A thread-safe table that routes events to their processors.
 *
 * @param <E> The base event type bounds for this table
 */
public interface DispatchTable<E extends Event> extends AutoCloseable {

    /**
     * Creates a new dispatch table with a resolver for unseen types and an initial
     * set of types to eagerly cache.
     *
     * @param resolver the resolver used to compute processors when encountering an event
     *                 type for the first time
     * @param warmUpTypes a collection of event types to eagerly cache during init
     * @param <T> the base event type bound
     * @return a new active dispatch table instance
     */
    static <T extends Event> @NotNull DispatchTable<T> create(
            @NotNull Resolver<T> resolver,
            @NotNull Collection<Class<? extends T>> warmUpTypes) {
        return new ClassValueDispatchTable<>(resolver, warmUpTypes);
    }

    /**
     * Returns an empty dispatch table instance.
     *
     * @param <T> the expected event type bound
     * @return an empty dispatch table
     */
    static <T extends Event> @NotNull DispatchTable<T> empty() {
        return EmptyDispatchTable.empty();
    }

    /**
     * Dispatches the given event to all processors mapped to its type.
     * <p>
     * This method must only be called if the caller can guarantee
     * this table has not been closed.
     *
     * @param event The event to post.
     */
    void dispatch(@NotNull E event);

    /**
     * Explicitly invalidates and purges all cached entries generated by this table.
     * <p>
     * Calling this method is strictly mandatory before discarding the table instance
     * to ensure that event types and handler references are released for garbage collection.
     * <p>
     * <b>Concurrency Requirement:</b> This method must never be called concurrently
     * with {@link #dispatch(Event)}. The invoking system must guarantee all executing
     * threads have exited the dispatch pathway before calling close.
     */
    @Override
    void close();
}
