package com.github.rcubedev.utils.event.impl.bus.dispatch.table;

import com.github.rcubedev.utils.event.api.Event;
import com.github.rcubedev.utils.event.api.EventProcessor;
import com.github.rcubedev.utils.event.api.TestEvent;
import com.github.rcubedev.utils.event.impl.bus.dispatch.table.resolver.Resolver;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Collections;
import java.util.List;
import java.util.Set;
import java.util.concurrent.atomic.AtomicReference;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class DispatchTableTests {

    @Mock
    private Resolver<Event> mockResolver;

    @Mock
    private DispatchTable<Event> mockFallbackTable;

    @Test
    void testPublicEmptyFactoryReturnsValidInstance() {
        DispatchTable<Event> table = DispatchTable.empty();
        TestEvent event = new TestEvent();

        assertNotNull(table, "The public factory method must never return null");

        assertDoesNotThrow(() -> table.dispatch(event), "Dispatching to an empty table must be a safe no-op");
        assertDoesNotThrow(table::close, "Closing an empty table must be a safe no-op");
    }

    @Test
    void testPublicEmptyFactoryReturnsSameInstance() {
        DispatchTable<Event> firstCall = DispatchTable.empty();
        DispatchTable<Event> secondCall = DispatchTable.empty();

        assertSame(firstCall, secondCall, "The empty factory should return a shared, immutable singleton instance");
    }

    @Test
    void testPublicCreateFactoryReturnsFunctionalActiveInstance() {
        boolean[] processorInvoked = {false};
        EventProcessor<Event> simpleProcessor = event -> processorInvoked[0] = true;

        when(mockResolver.resolve(TestEvent.class)).thenReturn(List.of(simpleProcessor));
        Set<Class<? extends Event>> warmUpTypes = Set.of(TestEvent.class);

        DispatchTable<Event> table = DispatchTable.create(mockResolver, DispatchTable::empty, warmUpTypes);
        TestEvent eventA = new TestEvent();

        assertNotNull(table, "The public create factory method must never return null");
        assertNotSame(DispatchTable.empty(), table, "Create factory must return a distinct active engine instance");

        table.dispatch(eventA);
        assertTrue(processorInvoked[0], "The active table instance generated by the factory should route events correctly");

        assertDoesNotThrow(table::close, "Closing the active table instance must execute successfully");
    }

    @Test
    void testClosedTableRoutesToActiveTable() {
        when(mockResolver.resolve(any())).thenReturn(Collections.emptyList());

        DispatchTable<Event> table = DispatchTable.create(mockResolver, () -> mockFallbackTable, Set.of(TestEvent.class));
        TestEvent event = new TestEvent();

        table.close();
        table.dispatch(event);

        verify(mockFallbackTable).dispatch(event);
    }

    @Test
    void testClosedTableThrowsWhenFallbackIsNull() {
        when(mockResolver.resolve(any())).thenReturn(Collections.emptyList());

        DispatchTable<Event> table = DispatchTable.create(mockResolver, () -> null, Set.of(TestEvent.class));
        table.close();

        assertThrows(IllegalStateException.class, () -> table.dispatch(new TestEvent()), "Closed table must throw when activeTable resolves to null");
    }

    @Test
    void testClosedTableThrowsWhenFallbackIsSelf() {
        when(mockResolver.resolve(any())).thenReturn(Collections.emptyList());

        AtomicReference<DispatchTable<Event>> tableHolder = new AtomicReference<>();

        DispatchTable<Event> table = DispatchTable.create(mockResolver, tableHolder::get, Set.of(TestEvent.class));
        tableHolder.set(table);

        table.close();
        assertThrows(IllegalStateException.class, () -> table.dispatch(new TestEvent()), "Closed table must throw when activeTable resolves to self");
    }
}