name: Build
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: |
            **/build/libs/*.jar
          if-no-files-found: error