package com.github.rcubedev.example.event.impl.bus.dispatch.table;

import com.github.rcubedev.example.event.api.Event;
import com.github.rcubedev.example.event.api.EventProcessor;
import com.github.rcubedev.example.event.api.TestEvent;
import com.github.rcubedev.example.event.impl.bus.dispatch.table.resolver.Resolver;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

class DispatchTableTests {

    @Test
    void testPublicEmptyFactoryReturnsValidInstance() {
        DispatchTable<Event> table = DispatchTable.empty();
        TestEvent event = new TestEvent();

        assertNotNull(table, "The public factory method must never return null");

        assertDoesNotThrow(() -> table.dispatch(event), 
                "Dispatching to an empty table must be a safe no-op");
        assertDoesNotThrow(table::close, 
                "Closing an empty table must be a safe no-op");
    }

    @Test
    void testPublicEmptyFactoryReturnsSameInstance() {
        DispatchTable<Event> firstCall = DispatchTable.empty();
        DispatchTable<Event> secondCall = DispatchTable.empty();

        assertSame(firstCall, secondCall, 
                "The empty factory should return a shared, immutable singleton instance");
    }

    @Test
    void testPublicCreateFactoryReturnsFunctionalActiveInstance() {
        boolean[] processorInvoked = {false};
        EventProcessor<Event> simpleProcessor = event -> processorInvoked[0] = true;

        Resolver<Event> mockResolver = type -> List.of(simpleProcessor);
        Set<Class<? extends Event>> warmUpTypes = Set.of(TestEvent.class);

        DispatchTable<Event> table = DispatchTable.create(mockResolver, warmUpTypes);
        TestEvent eventA = new TestEvent();

        assertNotNull(table, "The public create factory method must never return null");
        assertNotSame(DispatchTable.empty(), table, "Create factory must return a distinct active engine instance");

        table.dispatch(eventA);
        assertTrue(processorInvoked[0], "The active table instance generated by the factory should route events correctly");

        assertDoesNotThrow(table::close, "Closing the active table instance must execute successfully");
    }
}
